### ISSUE TITLE
how to walk the AST

### ISSUE THREAD

**Issue by YuaShizuki** [erezsh/plyplus#19]
can you tell me how can i walk the AST like in the ast module that comes with python

**Comment by erezsh** [comment]
You can use the SVisitor or STransformer classes for that.
See: https://github.com/erezsh/plyplus/blob/master/plyplus/strees.py#L326
The calculator example uses STransformer simply: https://github.com/erezsh/plyplus/blob/master/examples/calc.py

**Comment by YuaShizuki** [comment]
Ok thanks i got it working. I did'nt know that you could use t.tail to access child nodes.
