### ISSUE TITLE
Problem with hard coded path to temporary files, when starting two application instances from one code base.

### ISSUE THREAD

**Issue by marekslawinski** [erezsh/plyplus#25]
Consider two instances of application: 'development' and 'production'. Each on different project version (different commit). Now plyplus uses one hard coded location to store temporary files for both applications. Now when touching .wsgi following error occur:

Unable to create '/tmp/plyplus/plyplus_grammar_parsetab.py'
[Errno 13] Permission denied: '/tmp/plyplus/plyplus_grammar_parsetab.py'
Unable to create '/tmp/plyplus/parsetab_selector_g.py'
[Errno 13] Permission denied: '/tmp/plyplus/parsetab_selector_g.py'

which forcing to use production version temporary files (older version, used by users) with development version (newer, under development version).

**Comment by erezsh** [comment]
Would adding the version to the path solve the problem? (i.e. /tmp/plyplus-0.6.1/*)

**Comment by marekslawinski** [comment]
I've made  some investigation and found some low effort solution. Inside plyplus __init__.py there is line:

PLYPLUS_DIR = os.path.join(gettempdir(), 'plyplus')

you could use mkdtemp() function from tempfile python module, which always generates unique directory (i. e. /tmp/tmpvRQzVCplyplus /tmp/tmpWwD4tiplyplus). This should solve issue, but there is still problem with deleting this directories.

**Comment by erezsh** [comment]
The problem with deleting directories is what made me choose a fixed path in the first place. Also, it's better for performance to use a cached grammar (as long as it doesn't change ofc).

**Comment by joshuaali** [comment]
This should have been fixed by #29.

**Comment by marekslawinski** [comment]
Yes, this solution should fix my issue. Waiting for release. Thanks. :-)

**Comment by erezsh** [comment]
A new release (0.6.2) including this patch is now in PyPI.
