### ISSUE TITLE
Support for unicode tokens in grammars

### ISSUE THREAD

**Issue by Smattr** [erezsh/plyplus#27]
I'd like to be able to use unicode in tokens within my grammar. Currently, `'←'`. This isn't possible currently because the grammar parser tries to decode this as ascii.

What is your opinion on unicode in grammars? I'm happy to work on implementing it, but wanted to check if you had any strong opposition to this.

**Comment by erezsh** [comment]
I think it's a nice idea!

Include some tests in the patch, of course.
