### ISSUE TITLE
Grammar rule ordering problem (PEBKAC?)

### ISSUE THREAD

**Issue by erikvanzijst** [erezsh/plyplus#31]
This is quite likely user error, but I can't figure out why my parser fails when I simply reorder 2 of its rules:

```python
# success:
print Grammar("""
  @start: field value;

  value: 'bar';
  field: '\w+';

  WS: '[ \t]+' (%ignore);
""").parse('foo bar')

# fail (swapped field/value declaration order):
print Grammar("""
  @start: field value;

  field: '\w+';
  value: 'bar';

  WS: '[ \t]+' (%ignore);
""").parse('foo bar')
```

The latter grammar crashes with:

```
  File "grammar_test.py", line 21, in <module>
    """).parse('foo bar')
  File "/Users/evzijst/work/venv/bbql/lib/python2.7/site-packages/plyplus/plyplus.py", line 575, in parse
    return self._grammar.parse(text)
  File "/Users/evzijst/work/venv/bbql/lib/python2.7/site-packages/plyplus/plyplus.py", line 716, in parse
    raise ParseError('\n'.join(self.errors))
plyplus.plyplus.ParseError: Syntax error in input at 'bar' (type _ANON_0) line 1 col 5
Could not create parse tree!
```

N.B.
PlyPlus==0.6.2
ply==3.6

**Comment by erezsh** [comment]
Hi Erik,

The error is simple: '\w+' can match 'bar', so there is a collision. The tokens are evaluated by order, so switching the statements changes which one is chosen.
I suggest you use the (%unless ..) modifier:

  field: FIELD;
  value: VALUE;

FIELD: '\w+'
    (%unless
        VALUE: 'bar';
    );

**Comment by erikvanzijst** [comment]
Awesome, I'll give that a go!

**Comment by erikvanzijst** [comment]
I understand the issue tracker is probably not the ideal the platform for this, but adding unless to FIELD has the side effect of ruling out "bar" as a field (`parse('bar bar')`).

**Comment by erezsh** [comment]
Yes, one of PLY's requirements is that the tokenizer is deterministic..

What I usually do is add both tokens to the rule:

field: FIELD | VALUE;
