### ISSUE TITLE
Error trying to use `cache_grammar`

### ISSUE THREAD

**Issue by kyouko-taiga** [erezsh/plyplus#43]
Initializing a grammar object with the flag `cache_grammar` the following type error in Python 3.6:

```
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    grammar = Grammar(f.read(), auto_filter_tokens=False, cache_grammar=True)
  File "/lib/python3.5/site-packages/plyplus/plyplus.py", line 550, in __init__
    plyplus_cache_filename = PLYPLUS_DIR + '/%s-%s-%s.plyplus' % (tab_filename, hashlib.sha256(grammar).hexdigest(), __version__)
TypeError: Unicode-objects must be encoded before hashing
```

Looks like this could be solved by simply adding a `.encode()` after grammar (at line [550](https://github.com/erezsh/plyplus/blob/61056e44f7efe94bf519feae420dd385ae6ca812/plyplus/plyplus.py#L550)).
But then pickle will complain about being unable to pickle the grammar (at line [558](https://github.com/erezsh/plyplus/blob/61056e44f7efe94bf519feae420dd385ae6ca812/plyplus/plyplus.py#L558)).

**Comment by erezsh** [comment]
Please provide the code that caused this exception.

**Comment by kyouko-taiga** [comment]
Certainly!

```python
from plyplus import Grammar

if __name__ == '__main__':
    with open('grammar.g') as f:
        grammar = Grammar(f.read(), auto_filter_tokens=False, cache_grammar=True)
```

My grammar is rather large, but I don't think it's what's causing the problem.
I was able to reproduce the error with the same code and the `calc.g` grammar example.

**Comment by kyouko-taiga** [comment]
The second error though (raised by the `pickle` module) seems to be caused by the use of  from the fact that my grammar uses of the `(%unless ...)` macro.

Here's a minimal example of a problematic grammar:

```
NAME : '\w+'
     (%unless
         VAR: 'var';
     );
```

Bypassing the first issue (about the unicode-objects not being encoded), we can trigger the second error:

```python
grammar = Grammar(f.read())
pickle.dump(grammar, some_cache)

# Traceback (most recent call last):
#   File "main.py", line 9, in <module>
#     pickle.dump(grammar, f)
# AttributeError: Can't pickle local object 'Engine_PLY.add_token_unless.<locals>.t_token'
```

**Comment by erezsh** [comment]
The first error is very simple to fix.
But caching grammars with %unless appears to require a big structural change to the code. I'm a bit reluctant to do so, since right now I'm focusing my energy on other things.

How important is this feature to you? Is PLY's grammar caching insufficient for your needs?

Also, I've since rewritten plyplus as a new project, called Lark: https://github.com/erezsh/Lark
Right now it doesn't support caching grammars, but adding this feature there should be a lot easier. Would you consider switching to Lark if I add it the cache_grammar feature?

**Comment by kyouko-taiga** [comment]
Your new project looks promising! I'm still early in the development of my compiler, so switching to Lark seems quite reasonable. I'll give it a try as soon as I have time.

My current parser implementation is based on [funcparserlib](https://github.com/vlasovskikh/funcparserlib), which unfortunately can't handle left-recursion in an acceptable manner for my needs. I moved to plyplus as a mean to solve that issue and got rewarded with promising results, but the grammar parsing (which I guess also includes the parser generation) takes way too much time.

**Comment by erezsh** [comment]
Well, I've put the lessons I learned writing plyplus into Lark. For example, Transformers are much faster now, and so processing grammars became faster too. Also, my LALR parser generates much faster than PLY's (it's also 1/10th the lines of code).

Also, caching grammars in Lark is in my TODO list, so if it's a major hurdle for you, let me know and I will move it up the list.

**Comment by kyouko-taiga** [comment]
I've played a little with Lark, and it seems to be a perfect replacement for plyplus =D

The parser generation time is quite satisfactory, so I guess I can live without grammar caching for the time being, if you have more pressing issues to work on.

As far as I'm concerned, this issue can be closed.
