### ISSUE TITLE
Missing real License file

### ISSUE THREAD

**Issue by tigerfoot** [erezsh/plyplus#45]
The MIT license file cited in Readme doesn't point to anything real now.

I guess that the simpler fix is using the one of lark-parser and adding it to tgz next release on pypi.

**Comment by erezsh** [comment]
If you want to add a patch you're more than welcome.
Btw, is there a feature you're using in plyplus that lark-parser doesn't have?

**Comment by tigerfoot** [comment]
No in fact I was trying to refresh my openSUSE package of lark-parser, but the check part where tests are done doesn't work, (tar.gz available on pypi) and I discover they need plyplus ... But even with a package of plyplus it doesn't work .
sorry I'm away from my main keyboard actually. But will send reports there.
So as Iˆve understood lark is the replacement of this one right ;-)

**Comment by erezsh** [comment]
Wait, so the lark-parser tests try to import plyplus? It must be an error in the packaging if so. I'll look into it.
Yes, lark is a replacement for this one.

**Comment by erezsh** [comment]
So I checked the lark-parser tar.gz, and there is no mention of plyplus there..

**Comment by tigerfoot** [comment]
I'm so sorry to not agree ;-)

```
wget
tar -xzf lark-parser-0.4.1.tar.gz
cd lark-parser-0.4.1
grep -Ri plyplus *
docs/reference.md:Lark is a re-write of my previous parsing library, [PlyPlus](https://github.com/erezsh/plyplus).
tests/test_grammars.py:from plyplus import grammars
tests/test_grammars.py:from plyplus.plyplus import Grammar
tests/test_grammars.py:        g.parse(_read('../plyplus.py'))
tests/test_selectors.py:from plyplus.plyplus import Grammar, STree
tests/test_selectors.py:from plyplus.selector import selector
```

What's true is that lark git master doesn't contain anymore plyplus except in description.

**Comment by erezsh** [comment]
How dare you :P

I just uploaded lark-parser-0.5.0.tar.gz  (a release that was a long time coming)

Hope it fixes the issue.

**Comment by erezsh** [comment]
Closing since this is about Lark (and also resolved)
